## [ <-- Color Code: http://web.feather-s.kr:100/colors/ --> ] ##

## [ <-- Item Code: https://minecraftitemids.com/ --> ] ##
#                     ⌜ We Need Numerical ID ⌟           #

## <- Settings -> ##
LogPrefix: "§a[§bMagicPlugin§a]"

## <- CustomJoinMessage -> ##
Join:
  enable: true
  message: "§9[§a+§9] §7%player%"   #[ you can use %player% ]#

## <- CustomQuitMessage -> ##
Quit:
  enable: true
  message: "§9[§a-§9] §7%player%"   #[ you can use %player% ]#

## <- DiscordBot Settings -> ##
BotToken: "YOUR_BOT_TOKEN"
BotCommandPrefix: "!"

# [Channel ID] #
WelcomeByeChannelID: "YOUR_CHANNEL_ID"
VerifyChannelID: "YOUR_CHANNEL_ID"
ChatSyncChannelID: "YOUR_CHANNEL_ID"

# [Role ID] #
VerifiedRoleID: "YOUR_ROLE_ID"


## [ <-- By AMD_5900X -->] ##
## [ <-- Contact: 호예준#3840 -->] ##