#############################################################################################################################
#+=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=+#
#|          ____                                        __                        ___                                      |#
#|        /\  _`\                                     /\ \__    __              /\_ \              /'\_/`\                 |#
#|        \ \ \L\_\    ____    ____     __     ___    \ \ ,_\  /\_\      __     \//\ \      ____  /\      \                |#
#|         \ \  _\L   /',__\  /',__\  /'__`\ /' _ `\   \ \ \/  \/\ \   /'__`\     \ \ \    /',__\ \ \ \__\ \               |#
#|          \ \ \L\ \/\__, `\/\__, `\/\  __/ /\ \/\ \   \ \ \_  \ \ \ /\ \L\.\_    \_\ \_ /\__, `\ \ \ \_/\ \              |#
#|           \ \____/\/\____/\/\____/\ \____\\ \_\ \_\   \ \__\  \ \_\\ \__/.\_\   /\____\\/\____/  \ \_\\ \_\             |#
#|            \/___/  \/___/  \/___/  \/____/ \/_/\/_/    \/__/   \/_/ \/__/\/_/   \/____/ \/___/    \/_/ \/_/             |#
#|                                                                                                                         |#
#|                                           This is config file of EssentialsM                                            |#
#|                                            Thanks for downloading our plugin                                            |#
#|                                                                                                                         |#
#|                                            Copyright 2022, MagicPlugin Team                                             |#
#|                                                                                                                         |#
#+-------------------------------------------------------------------------------------------------------------------------+#
#|                                     Plugin Owner's DM: http://web.feather-s.kr/dm/                                      |#
#|                                     Color Code: http://web.feather-s.kr:100/colors/                                     |#
#+=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=+#
#############################################################################################################################


#+---------------------------------------------------Minecraft Settings----------------------------------------------------+#
LogPrefix: "§7§l|§r§6MP§r§7§l|§r"

#+--------CustomJoinQuitMessage--------+#
#|            [ %player% ]             |#
#+-------------------------------------+#
Join:
  enable: true
  message: "§9[§a+§9] §7%player%"
Quit:
  enable: true
  message: "§9[§a-§9] §7%player%"

#+----------------AFK------------------+#
#|  teleport when player didn't move   |#
#+-------------------------------------+#
AFK:
  enable: true
  time: 60 #[ seconds ]#
  message: "§9[§aAFK§9] §7%player%, You are §cAFK §7now."
  disable_message: "§9[§aAFK§9] §7%player%, You are §cnot §7AFK now."
  teleport:
    enable: true
    location:
      world: "world"
      x: 0.5
      y: 64
      z: 0.5

#+-----------CustomShopList------------+#
#| you need to generate other yml file |#
#+-------------------------------------+#
Shop:
  enable: true
  shops:
    - "example_shop.yml"

#+------------ChatChannel--------------+#
# |   [ %id%, %message%, %player% ]    |#
#+-------------------------------------+#
ChatChannel:
  enable: true
  message: "§9[§a%id% Channel§9] §7<%player%> §f%message%"

#+--------------------------------------------------Discord Bot Settings---------------------------------------------------+#
BotToken: "YOUR_BOT_TOKEN"
BotStatus:
  richPresence: "FEATHER ANARCHY"
  status: "online" #[ "online", "idle", "dnd", "invisible", "offline" ]#

#+--------EnableDiscordCommand---------+#
VerifyCommandEnabled: false
StatusCommandEnabled: true

#+-------------Channel ID--------------+#
VerifyChannelID: "YOUR_CHANNEL_ID"
ChatSyncChannelID: "YOUR_CHANNEL_ID"

#+---------------Role ID---------------+#
VerifiedRoleID: "YOUR_ROLE_ID"

#+----------ChaySync Settings----------+#
ChatSync:
  message: "%player% » %message%"   #[ you can use %player% / %message%]#
  joinMessage: "%player% joined the server!"  #[ you can use %player% ]#
  quitMessage: "%player% left the server!"  #[ you can use %player% ]#
  playerDeathMessage: "%cause%"  #[ you can use %player%, %cause% ]#
  messageReceivedFromDiscord: "§b[§6Discord§b] §7%user_name% » %message%"  #[ you can use %user_name% / %message% ]#
EnabledChatSync:
  chat: true
  join: true
  quit: true
  death: true