name: EssentialsM
main: kr.feathers.mc.MagicPluginMain
version: 1.3
description: ALL RIGHTS RESERVED.
authors: [ AMD_5900X, LICKER2689, Bruce0203 ]
api-version: 1.19

commands:
  mp:
    description: EssentialsM Command